### ISSUE TITLE
errors for python 2.6

### ISSUE THREAD

**Issue by davidtingsu** [m3xm/hikari-for-Jekyll#29]
```
bundle exec jekyll serve --watch
Configuration file: /Projects/hikari-for-Jekyll/_config.yml
            Source: /Projects/hikari-for-Jekyll
       Destination: /Projects/hikari-for-Jekyll/_site
      Generating...
  Liquid Exception: Failed to get header. in _posts/2014-01-27-hikari-styling-guide.markdown
jekyll 2.1.0 | Error:  Failed to get header.
```
I'm using ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin12.5.0] and upgraded to python 2.7.8 to fix it.
https://github.com/jekyll/jekyll/issues/1181
Perhaps we can use travis to run bundle exec jekyll serve --watch for all the different versions of python and ruby.

**Comment by ssorallen** [comment]
Python 2.6's last release was in 2010. I don't think it's worth trying to support it because it was superseded by 2.7 in July 2010: https://www.python.org/downloads/

Closing this because the fix is to upgrade to a more recent version of Python.
