### ISSUE TITLE
Merge master and GH-pages branches

### ISSUE THREAD

**Issue by orawalters** [m3xm/hikari-for-Jekyll#42]
There's no reason to have two duplicate branches
Instructions on how to do it:
1. Go into [repo settings](https://github.com/mx3m/hikari-for-jekyll/settings) and set `gh-pages` as default
2. Then go into [branches](https://github.com/mx3m/hikari-for-jekyll/branches) and delete `master`
3. ???
4. Profit.

**Comment by josephfusco** [comment]
:+1:  in favor of deleting master branch. :octocat:

**Comment by mx3m** [comment]
2 months late but done! Thanks for the tips :)
