### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Kimeiga** [m3xm/hikari-for-Jekyll#46]
This theme is amazingly unique! I was looking for a Jekyll theme on jekyllthemes.io that could really make my blog stand out, and I saw Hikari, and thought that this would be the one I could really build upon.

I love the full width, animated list of blog posts idea; very minimalist and content focused for a front page!

I decided that I wanted to have a feature image for each blog post and feature it within the list elements, and I figured it out! I also make lots of styling changes and changed the fonts, although there's a bit more work to do.

[My Blog](https://kimeiga.github.io/blog)

I really appreciate the work you put in to compartmentalizing the scss into different files, and using variables with the colors, fonts, and even spacing. It made it very easy to modify quickly, and actually taught me a lot about web design best practices.

Cheers!

**Comment by mx3m** [comment]
Hi @Kimeiga 

Thank you for the note! 

I haven't maintained this theme in forever. I see there is a dependency vulnerability somewhere. Probably worth fixing on your end directly.

Your blog looks great! I'm glad you could use Hikari as a base and learn from it!

**Comment by Kimeiga** [comment]
Thanks @mx3m ! Where is the dependency vulnerability (or how do you know of it?) ?

**Comment by mx3m** [comment]
Github tells me because I'm the owner of the repository. 

brianmario / yajl-ruby is the issue here. Version should be updated to latest in your fork.

**Comment by ssorallen** [comment]
The background images for each post on your blog look great on mobile. Nice work!

**Comment by Kimeiga** [comment]
Thanks guys!
